{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bytedance.android",
    "module": "aabresguard-plugin",
    "version": "0.1.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "52u44wjsjvbubledkcgexrtx64"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.bytedance.android",
          "module": "aabresguard-core",
          "version": {
            "requires": "0.1.11"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "bundletool"
            },
            {
              "group": "com.google.guava",
              "module": "guava"
            },
            {
              "group": "com.android.tools.build",
              "module": "gradle"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "aabresguard-plugin-0.1.11.jar",
          "url": "aabresguard-plugin-0.1.11.jar",
          "size": 21801,
          "sha512": "7cc62e0ad793350831ae64df757747299e479835495fd5a63a394c0c2b8fdb1b70bb269edaeb327c2b65b2ae9f50bf15be72a664b24df9b7229cafd988c60451",
          "sha256": "959b420cef5970910a17dc2f9e7cf27fed7309ac4f0ee35ac4ca56c560e5088e",
          "sha1": "16c99a6fbcd4cc9ad6de0d0cdae8586fbebbfe4f",
          "md5": "6b29d08e441c68f798f25f60ce1262b6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.3.61"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "bundletool"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.3.61"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "bundletool"
            }
          ]
        },
        {
          "group": "com.bytedance.android",
          "module": "aabresguard-core",
          "version": {
            "requires": "0.1.11"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "bundletool"
            },
            {
              "group": "com.google.guava",
              "module": "guava"
            },
            {
              "group": "com.android.tools.build",
              "module": "gradle"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "aabresguard-plugin-0.1.11.jar",
          "url": "aabresguard-plugin-0.1.11.jar",
          "size": 21801,
          "sha512": "7cc62e0ad793350831ae64df757747299e479835495fd5a63a394c0c2b8fdb1b70bb269edaeb327c2b65b2ae9f50bf15be72a664b24df9b7229cafd988c60451",
          "sha256": "959b420cef5970910a17dc2f9e7cf27fed7309ac4f0ee35ac4ca56c560e5088e",
          "sha1": "16c99a6fbcd4cc9ad6de0d0cdae8586fbebbfe4f",
          "md5": "6b29d08e441c68f798f25f60ce1262b6"
        }
      ]
    }
  ]
}
